### ISSUE TITLE
Random Events

### ISSUE THREAD

**Issue by lawrab** [dennis/slipstream#27]
# Overview
I want to play audio files or TTS randomly with a minimum interval only when in practice or race sessions in iRacing. This will be used to add encouraging audio.

# Key requirements
* Randomised event
* Only active during specified iRacing session types
* Executes a function e.g. play an audio file or TTS
* Metadata is required to determine which audio should be played
* Events can originate from random time and specific racing events (randomly selected)

# Randomise events
* Timer event with a minimum time between events
* Event randomly triggered after specified iRacing events e.g. IRacingDriverIncident min 3, max5 will trigger this between 3 to 5 occurrences of IRacingDriverIncident event

I am not sure if this should be done in a script or a plugin.

**Comment by dennis** [comment]
I think this might help you. It got a `timer_talk` that is invoked between 10 and 30s. If you press the UI buttons, there is a 50% chance for, that it will invoke `triggered_talk`. This makes sure that the `time_talk` is reset, so we dont have two TTS just after eachother.

```lua
-- to generate some test events
ui:create_button("relevant")   -- we might triggered_talk
ui:create_button("irrelevant") -- always ignored

-- this is triggered at random times
local timer_talk = function(delay)
	audio:say("Waited " .. tostring(delay) .. " seconds", 1.0)
end

-- this is triggered by relevant events
local triggered_talk = function()
	audio:say("Say something nice", 1)

	-- go back to normal
	timer_talk_setup()
end

function timer_talk_setup()
	local delay = math.random(10,30);

	ui:print("setup_random delay = " .. delay)

	core:debounce("random-wait", function()
		timer_talk(delay)

		-- setup next time
		timer_talk_setup()
	end, delay)
end

function triggered_talk_setup()
	local n = math.random(0,1);

	if n == 0 then
		-- To avoid that we get a "timer_talk" just after event triggered
		-- speech, we use debounce with 0 (immediately) thereby overwriting
		-- the timer_talk with our triggered_talk
		core:debounce("random-wait", triggered_talk, 0)
	else
		ui:print("Ignored event")
	end
end

timer_talk_setup()

function handle(event)
	ui:print(core:event_to_json(event))

	if event.EventType == "UIButtonTriggered" and event.Text == "relevant" then
		triggered_talk_setup()
	end
end
```
