### ISSUE TITLE
Text To Speech (Specific Twitch handle)

### ISSUE THREAD

**Issue by lawrab** [dennis/slipstream#29]
Accepts TTS command from Twitch for specific users.

For example, Sassy can tell Annie how to drive by using a command in Twitch chat.

Command users are whitelisted.

**Comment by dennis** [comment]
Something like this?

```lua
local whitelist = {}

whitelist["sassy_mcsassypants"] = true

function string.starts(String,Start)
   return string.sub(String,1,string.len(Start))==Start
end

function handle(event)
	if(event.EventType == "TwitchReceivedMessage") then
		if string.starts(event.Message, "!say ") then
			if whitelist[string.lower(event.From)] then
				local text = string.lower(string.sub(event.Message, 6))
				audio:say(text, 1.0)
			else
				twitch:send_channel_message(event.From .. ": You are not whitelisted to use !say")
			end
		end
	end
end
```

Could be expanded with the `state` functions, so you can maintain the list via commands.

**Comment by lawrab** [comment]
Used this implementation, added another dictionary to translate the name to something a bit more ear-friendly, will consolidate these at somepoint

**Comment by lawrab** [comment]
Closing this, the example provided by @dennis used as the basis to expand on this
